### ISSUE TITLE
Unable to parse nested array

### ISSUE THREAD

**Issue by jwu-au** [Kralizek/AWSSecretsManagerConfigurationExtensions#11]
Hi @Kralizek ,

Just trying to set a config in aws secrets manager like below:
```json
{
  "HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "Selz Databases",
        "Uri": "http://127.0.0.1:44444/healthz-databases"
      },
      {
        "Name": "Selz Services",
        "Uri": "http://127.0.0.1:44444/healthz-services"
      },
      {
        "Name": "Selz Endpoints",
        "Uri": "http://127.0.0.1:44444/healthz-endpoints"
      },
      {
        "Name": "S3 Buckets",
        "Uri": "http://127.0.0.1:44444/healthz-buckets"
      }
    ]
  }
}
```

It throws exception:
```
$exception    {System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JProperty'.
   at Kralizek.Extensions.Configuration.Internal.SecretsManagerConfigurationProvider.ExtractValues(JToken token, String prefix)+MoveNext()
   at Kralizek.Extensions.Configuration.Internal.SecretsManagerConfigurationProvider.ExtractValues(JToken token, String prefix)+MoveNext()
   at Kralizek.Extensions.Configuration.Internal.SecretsManagerConfigurationProvider.ExtractValues(JToken token, String prefix)+MoveNext()
   at Kralizek.Extensions.Configuration.Internal.SecretsManagerConfigurationProvider.LoadAsync()
   at Kralizek.Extensions.Configuration.Internal.SecretsManagerConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Selz.HealthChecks.Web.Program.Main(String[] args) in D:\Source\selz\Services.HealthChecks\src\Selz.HealthChecks.Web\Program.cs:line 16}    System.InvalidCastException
```

Can you have a simple test that it seems can't parse nested json array correctly?

Thank you

**Comment by jwu-au** [comment]
Please consider below fixes:
```c#
IEnumerable<(string key, string value)> ExtractValues(JToken token, string prefix)
{
    switch (token)
    {
        case JArray array:
        {
            for (var i = 0; i < array.Count; i++)
            {
                var key = $"{prefix}{ConfigurationPath.KeyDelimiter}{i}";
                foreach (var item in ExtractValues(array[i], key))
                {
                    yield return (item.key, item.value);
                }
            }

            break;
        }
        case JObject jObject:
        {
            foreach (var property in jObject.Properties())
            {
                var key = $"{prefix}{ConfigurationPath.KeyDelimiter}{property.Name}";

                if (property.Value.HasValues)
                {
                    foreach (var item in ExtractValues(property.Value, key))
                    {
                        yield return (item.key, item.value);
                    }
                }
                else
                {
                    var value = property.Value.ToString();
                    yield return (key, value);
                }
            }

            break;
        }
        default:
            throw new NotSupportedException($"cannot parse {token}");
    }
}
```

I can do a PR with test properly.

**Comment by Kralizek** [comment]
Hi @jwu-au,

Thank you for sharing this use case. Please make a PR so that I can see where the changes would affect the codebase.

**Comment by jwu-au** [comment]
Hi @Kralizek ,

Please review the PR:
https://github.com/Kralizek/AWSSecretsManagerConfigurationExtensions/pull/12

Thanks,
Jing
